#!/usr/bin/env node

var inquirer = require('inquirer'),
  fs = require('fs'),
  chalk = require('chalk'),
  toClipboard = require('to-clipboard'),
  choices = require('./lib/choices'),
  fuzzy = require('./lib/fuzzy'),
  getGeojson = require('./'),
  argv = require('yargs')
    .usage('Get GeoJSON\n$0')
    .boolean('all')
    .describe('all', 'show files that are bigger than 2MB')
    .help('help')
    .argv;

var base = 'https://s3.amazonaws.com/geojson-please/';
var naturalEarthSlug = 'naturalearth-3.3.0';
var license = 'SOURCE: http://www.naturalearthdata.com/ Public Domain (no restrictions)';

var options = {
  all: argv.all
};

if (argv._[0]) {
  getGeojson(argv._[0], function (res, file) {
    if (argv._[0] === '--') {
      res.pipe(process.stdout);
    } else {
      res
        .on('end', function() {
          console.log(chalk.green('✓ ') + chalk.bold('saved as ' + file.original));
          console.log(license);
        })
        .pipe(fs.createWriteStream(file.original));
    }
  });
  return;
}

inquirer.prompt(choices(options), function(answers) {
  var url = base + naturalEarthSlug + '/' + answers.file;
  if (answers.output === 'URL to Clipboard') {
    toClipboard(url);
    console.log('');
    console.log(chalk.green('✓ ') + chalk.bold('copied url to clipboard'));
    console.log(url);
    console.log(license);
  } else {
    getGeojson(answers.file, function(res) {
      res
        .on('end', function() {
          console.log('');
          console.log(chalk.green('✓ ') + chalk.bold('saved as ' + answers.file));
          console.log(license);
        })
        .pipe(fs.createWriteStream(answers.file));
    });
  }
});
